version: "2"
exclude_patterns:
  - "**/test.py"
  - "**/migrations/*.py"
  - "backend/apps/main/static/*"
  - "**/*.test.js"

plugins:
  pep8:
    enabled: true
  radon:
    enabled: true
  SonarPython:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: true

