version: "2"
exclude_patterns:
  - "**/*.js"
  - "**/test.py"
  - "**/migrations/*.py"
  - "!frontend/src/*"

plugins:
  pep8:
    enabled: true
  radon:
    enabled: true
  SonarPython:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: true

