version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      args:
        mode: dev
    command: python3 manage.py runserver 0.0.0.0:3001
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.dev
    volumes:
      - ./backend:/code
      - stats:/code/stats
    ports:
      - "3001:3001"
      - "5432:5432"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        mode: dev
        UID: 2000
        GID: 2000
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
      - stats:/usr/src/app/stats
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PUBLIC_URL=/wp
      - CI=true
  webserver:
    build:
      context: ./webserver
      args:
        mode: dev
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend

volumes:
  stats:
  db_data:
